PHASE1_TWEAKS = [

    {
        "id": "disable_superfetch",
        "name": "Matikan Superfetch (SSD Only)",
        "description": "Superfetch didesain untuk HDD. Di SSD justru menambah write cycle sia-sia.",
        "detail": "Service SysMain (Superfetch) melakukan pre-loading data ke RAM berdasarkan pola penggunaan. Di HDD ini berguna karena mempercepat load. Di SSD ini tidak berguna dan justru menambah penulisan yang tidak perlu.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "SysMain", "state": "disabled"}],
        "needs_restart": True,
        "rollback": True,
        "tags": ["performance", "ssd", "service"],
    },
    {
        "id": "disable_windows_search",
        "name": "Matikan Windows Search Indexing",
        "description": "Windows Search mengindex semua file terus-menerus, memakan disk I/O dan RAM.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "WSearch", "state": "disabled"}],
        "needs_restart": False,
        "rollback": True,
        "tags": ["performance", "disk", "service"],
    },
    {
        "id": "disable_print_spooler",
        "name": "Matikan Print Spooler",
        "description": "Matikan service print jika tidak punya printer. Hemat RAM dan kurangi attack surface.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "Spooler", "state": "disabled"}],
        "needs_restart": False,
        "rollback": True,
        "tags": ["service", "printer"],
    },
    {
        "id": "disable_fax",
        "name": "Matikan Fax Service",
        "description": "Service fax bawaan Windows. Hampir tidak ada yang membutuhkan ini.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "Fax", "state": "disabled"}],
        "needs_restart": False,
        "rollback": True,
        "tags": ["service"],
    },
    {
        "id": "disable_xbox_services",
        "name": "Matikan Xbox Services",
        "description": "Matikan service Xbox jika tidak pakai Xbox. Hemat RAM dan startup time.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [
            {"service": "XblGameSave", "state": "disabled"},
            {"service": "XboxNetApiSvc", "state": "disabled"},
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["service", "xbox", "gaming"],
    },
    {
        "id": "disable_geolocation",
        "name": "Matikan Geolocation Service",
        "description": "Matikan layanan lokasi GPS yang tidak dibutuhkan di desktop.",
        "phase": 1,
        "category": "Privacy",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "lfsvc", "state": "disabled"}],
        "needs_restart": False,
        "rollback": True,
        "tags": ["privacy", "location"],
    },
    {
        "id": "disable_parental_controls",
        "name": "Matikan Parental Controls",
        "description": "Matikan service kontrol orang tua jika tidak dibutuhkan.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "WpcMonSvc", "state": "disabled"}],
        "needs_restart": False,
        "rollback": True,
        "tags": ["service"],
    },
    {
        "id": "disable_retail_demo",
        "name": "Matikan Retail Demo",
        "description": "Service untuk display toko. Selalu aman dimatikan di PC pribadi.",
        "phase": 1,
        "category": "Services",
        "risk": "safe",
        "type": "service",
        "actions": [{"service": "RetailDemo", "state": "disabled"}],
        "needs_restart": False,
        "rollback": True,
        "tags": ["service"],
    },
    {
        "id": "cleanup_temp_files",
        "name": "Bersihkan File Temporary",
        "description": "Hapus file sampah yang menumpuk di folder Temp, Prefetch, dan log sistem.",
        "detail": "Membersihkan: %TEMP%, C:\\Windows\\Temp, C:\\Windows\\Prefetch, C:\\Windows\\SoftwareDistribution\\Download, thumbnail cache, Windows Error Reporting files.",
        "phase": 1,
        "category": "Disk",
        "risk": "safe",
        "type": "cmd",
        "actions": [
            {"command": r"del /q /f /s %TEMP%\* 2>nul"},
            {"command": r"del /q /f /s C:\Windows\Temp\* 2>nul"},
            {"command": r"del /q /f /s C:\Windows\Prefetch\* 2>nul"},
            {"command": r"del /q /f /s C:\Windows\SoftwareDistribution\Download\* 2>nul"},
        ],
        "needs_restart": False,
        "rollback": False,
        "tags": ["disk", "cleanup", "temp"],
    },
    {
        "id": "reduce_visual_effects",
        "name": "Kurangi Animasi Windows",
        "description": "Matikan animasi fade/slide/shadow. GUI jadi terasa lebih responsif.",
        "detail": "Windows menjalankan 20+ animasi UI yang memakan CPU/GPU. Terutama terasa di PC tanpa GPU dedicated. Mode ini mematikan animasi buka/tutup jendela, shadow, dan smooth scrolling.",
        "phase": 1,
        "category": "UI",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {
                "path": r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects",
                "key": "VisualFXSetting",
                "value": 2,
                "reg_type": "DWORD",
            },
            {
                "path": r"HKCU\Control Panel\Desktop",
                "key": "MenuShowDelay",
                "value": "0",
                "reg_type": "SZ",
            },
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["ui", "performance", "animation"],
    },
    {
        "id": "disable_telemetry",
        "name": "Matikan Windows Telemetry",
        "description": "Nonaktifkan layanan yang mengirim data diagnostik dan usage statistics ke Microsoft.",
        "detail": "Windows secara default mengirim crash report, usage statistics, dan diagnostic data secara real-time. Tweak ini mematikan service DiagTrack dan dmwappushservice, serta set AllowTelemetry ke 0 via registry.",
        "phase": 1,
        "category": "Privacy",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {
                "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection",
                "key": "AllowTelemetry",
                "value": 0,
                "reg_type": "DWORD",
            },
            {
                "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection",
                "key": "AllowTelemetry",
                "value": 0,
                "reg_type": "DWORD",
            },
        ],
        "needs_restart": True,
        "rollback": True,
        "tags": ["privacy", "telemetry", "microsoft"],
    },
    {
        "id": "disable_telemetry_services",
        "name": "Matikan Telemetry Services",
        "description": "Matikan service DiagTrack dan WAP Push yang mengirim data ke Microsoft.",
        "phase": 1,
        "category": "Privacy",
        "risk": "safe",
        "type": "service",
        "actions": [
            {"service": "DiagTrack", "state": "disabled"},
            {"service": "dmwappushservice", "state": "disabled"},
        ],
        "needs_restart": True,
        "rollback": True,
        "tags": ["privacy", "telemetry", "service"],
    },
    {
        "id": "disable_scheduled_tasks",
        "name": "Matikan Scheduled Tasks Tidak Perlu",
        "description": "Matikan tugas otomatis Windows yang menyebabkan CPU dan disk spike tiba-tiba.",
        "detail": "Tasks yang dimatikan: Compatibility Appraiser, ProgramDataUpdater, CEIP Consolidator, DiskDiagnostic, Feedback DmClient, WinSAT, QueueReporting.",
        "phase": 1,
        "category": "Performance",
        "risk": "safe",
        "type": "task",
        "actions": [
            {"task_path": r"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser", "state": "disable"},
            {"task_path": r"\Microsoft\Windows\Application Experience\ProgramDataUpdater", "state": "disable"},
            {"task_path": r"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator", "state": "disable"},
            {"task_path": r"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector", "state": "disable"},
            {"task_path": r"\Microsoft\Windows\Feedback\Siuf\DmClient", "state": "disable"},
            {"task_path": r"\Microsoft\Windows\Maintenance\WinSAT", "state": "disable"},
            {"task_path": r"\Microsoft\Windows\Windows Error Reporting\QueueReporting", "state": "disable"},
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["performance", "scheduled_task"],
    },
    {
        "id": "ultimate_performance",
        "name": "Aktifkan Ultimate Performance",
        "description": "Power plan tersembunyi dari Microsoft yang menonaktifkan semua throttling CPU.",
        "detail": "Konsumsi listrik naik ~5-15W. Tidak disarankan untuk laptop yang sering pakai baterai.",
        "phase": 1,
        "category": "Power",
        "risk": "safe",
        "type": "cmd",
        "actions": [
            {"command": "powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61"},
            {"command": "powercfg /setactive SCHEME_MIN"},
        ],
        "needs_restart": False,
        "rollback": True,
        "rollback_cmd": "powercfg /setactive SCHEME_BALANCED",
        "tags": ["power", "performance"],
    },
    {
        "id": "disable_hibernation",
        "name": "Nonaktifkan Hibernasi",
        "description": "Hapus hiberfil.sys (4-32 GB) dan nonaktifkan Fast Startup.",
        "detail": "Menonaktifkan hibernasi menghapus file hiberfil.sys yang bisa berukuran sebesar RAM. Juga menonaktifkan Fast Startup (hybrid hibernate) sehingga PC melakukan cold boot bersih setiap nyala.",
        "phase": 1,
        "category": "Disk",
        "risk": "safe",
        "type": "cmd",
        "actions": [{"command": "powercfg -h off"}],
        "needs_restart": False,
        "rollback": True,
        "rollback_cmd": "powercfg -h on",
        "tags": ["disk", "power", "hiberfil"],
    },
    {
        "id": "disable_background_apps",
        "name": "Matikan Background Apps (UWP)",
        "description": "Nonaktifkan aplikasi UWP yang berjalan di background tanpa terlihat.",
        "phase": 1,
        "category": "Performance",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {
                "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications",
                "key": "GlobalUserDisabled",
                "value": 1,
                "reg_type": "DWORD",
            }
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["performance", "uwp", "background"],
    },
    {
        "id": "disable_usb_selective_suspend",
        "name": "Matikan USB Selective Suspend",
        "description": "Cegah jeda 1-2 detik pada mouse/keyboard setelah idle karena port USB di-sleep-kan.",
        "phase": 1,
        "category": "Input",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {
                "path": r"HKLM\SYSTEM\CurrentControlSet\Services\USB",
                "key": "DisableSelectiveSuspend",
                "value": 1,
                "reg_type": "DWORD",
            }
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["input", "usb", "mouse"],
    },
    {
        "id": "disable_mouse_acceleration",
        "name": "Matikan Mouse Acceleration",
        "description": "Hapus 'Enhance Pointer Precision' agar mouse terasa 1:1 tanpa acceleration layer.",
        "phase": 1,
        "category": "Input",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {"path": r"HKCU\Control Panel\Mouse", "key": "MouseSpeed", "value": "0", "reg_type": "SZ"},
            {"path": r"HKCU\Control Panel\Mouse", "key": "MouseThreshold1", "value": "0", "reg_type": "SZ"},
            {"path": r"HKCU\Control Panel\Mouse", "key": "MouseThreshold2", "value": "0", "reg_type": "SZ"},
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["input", "mouse", "gaming"],
    },
    {
        "id": "disable_delivery_optimization",
        "name": "Matikan Delivery Optimization (P2P)",
        "description": "Cegah Windows menjadikan PC sebagai seeder update ke komputer lain via internet.",
        "phase": 1,
        "category": "Network",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {
                "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization",
                "key": "DODownloadMode",
                "value": 0,
                "reg_type": "DWORD",
            }
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["network", "privacy", "bandwidth"],
    },
    {
        "id": "fix_quick_access",
        "name": "Fix File Explorer Quick Access",
        "description": "Perbaiki freeze File Explorer yang disebabkan Quick Access cache corrupt.",
        "phase": 1,
        "category": "UI",
        "risk": "safe",
        "type": "registry",
        "actions": [
            {
                "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer",
                "key": "ShowRecent",
                "value": 0,
                "reg_type": "DWORD",
            },
            {
                "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer",
                "key": "ShowFrequent",
                "value": 0,
                "reg_type": "DWORD",
            },
        ],
        "needs_restart": False,
        "rollback": True,
        "tags": ["ui", "explorer"],
    },
]
